[FilterPlugin]
; This file is used to specify which files and folders should be included in the plugin package
; Only list additional files/folders here that are NOT automatically included

; Include README.md
/README.md
